version: "3.9"

services:
  backend:
    build: .
    container_name: backend-py
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - conexao

  postgres:
    image: postgres:16
    container_name: banco-postgres
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - conexao

  pgadmin:
    image: dpage/pgadmin4
    container_name: pg-admin
    env_file: .env
    ports:
      - "15432:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    depends_on:
      - postgres
    networks:
      - conexao

networks:
  conexao:

volumes:
  pgdata: